FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw .
COPY pom.xml .
RUN ./mvnw -q dependency:resolve

COPY src ./src
RUN ./mvnw -q package -DskipTests

EXPOSE 8080
CMD ["java", "-jar", "target/*.jar"]